language: node_js
node_js:
  - '10'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
