language: node_js
cache: yarn
node_js:
  - '13'
sudo: false

branches:
  only:
    - dev

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  local_dir: dist
  fqdn: dmostovyi.com
  on:
    branch: dev
